const MOCK_PROGRAMS = [
  { id: 1, title: 'Musculation Fondamentale', description: 'Programme complet pour développer force et masse musculaire. Idéal pour les débutants souhaitant acquérir de solides bases.', category: 'Musculation', difficulty: 'Débutant', weeks: 8, sessionsPerWeek: 3, sessionMinutes: 60, price: 35000, oldPrice: 45000, coach: 'Jean-Pierre Mbarga', coachAvatar: null, city: 'Douala', rating: 4.8, reviews: 64, enrolled: 210, type: 'En présentiel', popular: true, recommended: true, image: null, color: '#16A34A' },
  { id: 2, title: 'Cardio Intensif & HIIT', description: 'Programme haute intensité pour brûler les graisses et améliorer votre endurance cardiovasculaire.', category: 'Cardio', difficulty: 'Intermédiaire', weeks: 6, sessionsPerWeek: 4, sessionMinutes: 45, price: 28000, oldPrice: null, coach: 'Carine Atangana', coachAvatar: null, city: 'Yaoundé', rating: 4.6, reviews: 42, enrolled: 175, type: 'Mixte', popular: true, recommended: false, image: null, color: '#F97316' },
  { id: 3, title: 'Yoga & Bien-être', description: 'Programme holistique combinant yoga, méditation et techniques de respiration pour un équilibre corps-esprit.', category: 'Yoga', difficulty: 'Débutant', weeks: 10, sessionsPerWeek: 3, sessionMinutes: 75, price: 40000, oldPrice: null, coach: 'Lydie Essomba', coachAvatar: null, city: 'Douala', rating: 4.9, reviews: 88, enrolled: 320, type: 'En présentiel', popular: true, recommended: true, image: null, color: '#8B5CF6' },
  { id: 4, title: 'CrossFit Performance', description: "Entraînement fonctionnel pour développer force, vitesse, agilité et endurance comme un athlète.", category: 'CrossFit', difficulty: 'Avancé', weeks: 12, sessionsPerWeek: 5, sessionMinutes: 90, price: 55000, oldPrice: 65000, coach: 'Samuel Tchinda', coachAvatar: null, city: 'Yaoundé', rating: 4.7, reviews: 35, enrolled: 95, type: 'En présentiel', popular: false, recommended: true, image: null, color: '#DC2626' },
  { id: 5, title: 'Boxe & Self-Défense', description: 'Apprenez les bases de la boxe anglaise tout en développant réflexes, coordination et confiance en soi.', category: 'Boxe', difficulty: 'Débutant', weeks: 8, sessionsPerWeek: 3, sessionMinutes: 60, price: 30000, oldPrice: null, coach: 'Patrick Elokobi', coachAvatar: null, city: 'Douala', rating: 4.5, reviews: 28, enrolled: 130, type: 'En présentiel', popular: false, recommended: false, image: null, color: '#2563EB' },
  { id: 6, title: 'Danse & Cardio Fusion', description: 'Brûlez des calories en vous amusant avec des chorégraphies variées sur des rythmes Afro, Zouk et Hip-Hop.', category: 'Danse', difficulty: 'Débutant', weeks: 6, sessionsPerWeek: 3, sessionMinutes: 50, price: 22000, oldPrice: null, coach: 'Sarah Ndjock', coachAvatar: null, city: 'Yaoundé', rating: 4.7, reviews: 52, enrolled: 245, type: 'En présentiel', popular: true, recommended: true, image: null, color: '#EC4899' },
  { id: 7, title: 'CrossFit Fondamentaux', description: 'Initiation progressive aux mouvements fonctionnels et WODs pour préparer le corps aux entraînements intenses.', category: 'CrossFit', difficulty: 'Débutant', weeks: 4, sessionsPerWeek: 3, sessionMinutes: 60, price: 15000, oldPrice: 20000, coach: 'Samuel Tchinda', coachAvatar: null, city: 'Yaoundé', rating: 4.4, reviews: 19, enrolled: 78, type: 'Mixte', popular: false, recommended: false, image: null, color: '#DC2626' },
  { id: 8, title: 'Pilates & Posture', description: "Renforcez votre ceinture abdominale et améliorez votre posture grâce à la méthode Pilates.", category: 'Pilates', difficulty: 'Débutant', weeks: 8, sessionsPerWeek: 2, sessionMinutes: 55, price: 25000, oldPrice: null, coach: 'Lydie Essomba', coachAvatar: null, city: 'Douala', rating: 4.8, reviews: 41, enrolled: 160, type: 'En présentiel', popular: false, recommended: false, image: null, color: '#06B6D4' },
  { id: 9, title: 'Fitness Prénatal', description: 'Programme adapté aux femmes enceintes pour maintenir une activité physique sécuritaire et bénéfique.', category: 'Bien-être', difficulty: 'Débutant', weeks: 12, sessionsPerWeek: 2, sessionMinutes: 45, price: 35000, oldPrice: null, coach: 'Carine Atangana', coachAvatar: null, city: 'Yaoundé', rating: 4.9, reviews: 33, enrolled: 85, type: 'En présentiel', popular: false, recommended: true, image: null, color: '#F43F5E' },
  { id: 10, title: 'Nutrition & Transformation', description: 'Programme complet combinant nutrition personnalisée et entraînement pour une transformation durable.', category: 'Nutrition', difficulty: 'Intermédiaire', weeks: 12, sessionsPerWeek: 4, sessionMinutes: 60, price: 65000, oldPrice: 80000, coach: 'Jean-Pierre Mbarga', coachAvatar: null, city: 'Douala', rating: 4.7, reviews: 56, enrolled: 200, type: 'Mixte', popular: true, recommended: false, image: null, color: '#16A34A' },
  { id: 11, title: 'Athlétisme Sprint', description: 'Améliorez votre vitesse et explosivité avec des exercices de sprint et pliométrie.', category: 'Athlétisme', difficulty: 'Avancé', weeks: 8, sessionsPerWeek: 4, sessionMinutes: 75, price: 40000, oldPrice: null, coach: 'Patrick Elokobi', coachAvatar: null, city: 'Douala', rating: 4.3, reviews: 15, enrolled: 55, type: 'En présentiel', popular: false, recommended: false, image: null, color: '#7C3AED' },
  { id: 12, title: 'Natation Perfectionnement', description: 'Perfectionnez vos techniques de nage avec des séances en piscine encadrées par un coach spécialisé.', category: 'Natation', difficulty: 'Intermédiaire', weeks: 10, sessionsPerWeek: 3, sessionMinutes: 60, price: 45000, oldPrice: null, coach: 'Sarah Ndjock', coachAvatar: null, city: 'Limbe', rating: 4.6, reviews: 22, enrolled: 65, type: 'En présentiel', popular: false, recommended: false, image: null, color: '#0EA5E9' },
  { id: 13, title: 'Full Body Challenge', description: "Défiez votre corps avec un programme complet sollicitant tous les groupes musculaires à chaque séance.", category: 'Musculation', difficulty: 'Intermédiaire', weeks: 6, sessionsPerWeek: 4, sessionMinutes: 50, price: 20000, oldPrice: null, coach: 'Samuel Tchinda', coachAvatar: null, city: 'Bafoussam', rating: 4.5, reviews: 38, enrolled: 145, type: 'Mixte', popular: true, recommended: false, image: null, color: '#16A34A' },
  { id: 14, title: 'Yoga Vinyasa Flow', description: 'Enchaînez les postures en fluidité pour un travail cardiovasculaire doux et une relaxation profonde.', category: 'Yoga', difficulty: 'Intermédiaire', weeks: 8, sessionsPerWeek: 3, sessionMinutes: 70, price: 32000, oldPrice: 38000, coach: 'Lydie Essomba', coachAvatar: null, city: 'Douala', rating: 4.8, reviews: 47, enrolled: 190, type: 'En présentiel', popular: false, recommended: true, image: null, color: '#8B5CF6' },
  { id: 15, title: 'Cardio Dance Afro', description: 'Un mix explosif de danse afro et d\'exercices cardio pour un défoulement garanti !', category: 'Danse', difficulty: 'Débutant', weeks: 4, sessionsPerWeek: 2, sessionMinutes: 45, price: 12000, oldPrice: null, coach: 'Sarah Ndjock', coachAvatar: null, city: 'Yaoundé', rating: 4.9, reviews: 71, enrolled: 280, type: 'En présentiel', popular: true, recommended: false, image: null, color: '#EC4899' },
  { id: 16, title: 'Musculation Prise de Masse', description: 'Programme intensif pour maximiser la prise de masse musculaire avec un suivi nutritionnel personnalisé.', category: 'Musculation', difficulty: 'Avancé', weeks: 12, sessionsPerWeek: 5, sessionMinutes: 90, price: 70000, oldPrice: 85000, coach: 'Jean-Pierre Mbarga', coachAvatar: null, city: 'Douala', rating: 4.6, reviews: 29, enrolled: 88, type: 'En présentiel', popular: false, recommended: false, image: null, color: '#16A34A' },
  { id: 17, title: 'Bien-être & Méditation', description: 'Apprenez à gérer le stress et l\'anxiété grâce à des techniques de méditation et de pleine conscience.', category: 'Bien-être', difficulty: 'Débutant', weeks: 8, sessionsPerWeek: 2, sessionMinutes: 40, price: 18000, oldPrice: null, coach: 'Carine Atangana', coachAvatar: null, city: 'Yaoundé', rating: 4.7, reviews: 63, enrolled: 230, type: 'En ligne', popular: true, recommended: true, image: null, color: '#F43F5E' },
  { id: 18, title: 'Boxe Avancée & Compétition', description: 'Préparez-vous à la compétition avec un entraînement de boxe intensif et technique.', category: 'Boxe', difficulty: 'Avancé', weeks: 16, sessionsPerWeek: 5, sessionMinutes: 120, price: 80000, oldPrice: null, coach: 'Patrick Elokobi', coachAvatar: null, city: 'Douala', rating: 4.4, reviews: 11, enrolled: 35, type: 'En présentiel', popular: false, recommended: false, image: null, color: '#2563EB' },
  { id: 19, title: 'Pilates Réformateur', description: 'Utilisez le réformateur Pilates pour un travail en profondeur des muscles stabilisateurs et posturaux.', category: 'Pilates', difficulty: 'Intermédiaire', weeks: 8, sessionsPerWeek: 2, sessionMinutes: 50, price: 38000, oldPrice: 45000, coach: 'Lydie Essomba', coachAvatar: null, city: 'Douala', rating: 4.8, reviews: 19, enrolled: 75, type: 'En présentiel', popular: false, recommended: false, image: null, color: '#06B6D4' },
  { id: 20, title: 'CrossFit Team Challenge', description: 'Rejoignez une équipe et participez à des WODs collectifs pour repousser vos limites ensemble.', category: 'CrossFit', difficulty: 'Intermédiaire', weeks: 8, sessionsPerWeek: 4, sessionMinutes: 75, price: 35000, oldPrice: null, coach: 'Samuel Tchinda', coachAvatar: null, city: 'Yaoundé', rating: 4.5, reviews: 27, enrolled: 110, type: 'Mixte', popular: false, recommended: true, image: null, color: '#DC2626' },
  { id: 21, title: 'Natation Débutant Adulte', description: "Apprenez à nager à votre rythme avec un coach patient et bienveillant dans une ambiance détendue.", category: 'Natation', difficulty: 'Débutant', weeks: 8, sessionsPerWeek: 2, sessionMinutes: 45, price: 25000, oldPrice: null, coach: 'Sarah Ndjock', coachAvatar: null, city: 'Garoua', rating: 4.5, reviews: 14, enrolled: 48, type: 'En présentiel', popular: false, recommended: false, image: null, color: '#0EA5E9' },
  { id: 22, title: 'Cardio & Renforcement', description: 'Combinez cardio et renforcement musculaire pour des résultats visibles rapidement.', category: 'Cardio', difficulty: 'Débutant', weeks: 4, sessionsPerWeek: 3, sessionMinutes: 40, price: 15000, oldPrice: null, coach: 'Carine Atangana', coachAvatar: null, city: 'Bamenda', rating: 4.6, reviews: 31, enrolled: 120, type: 'Mixte', popular: false, recommended: false, image: null, color: '#F97316' },
  { id: 23, title: 'Musculation Street Workout', description: 'Utilisez votre poids de corps et le mobilier urbain pour un entraînement fonctionnel sans équipement.', category: 'Musculation', difficulty: 'Intermédiaire', weeks: 6, sessionsPerWeek: 4, sessionMinutes: 50, price: 10000, oldPrice: null, coach: 'Patrick Elokobi', coachAvatar: null, city: 'Douala', rating: 4.3, reviews: 25, enrolled: 165, type: 'Mixte', popular: false, recommended: false, image: null, color: '#16A34A' },
  { id: 24, title: 'Yoga Prénatal', description: 'Pratique douce du yoga adaptée aux femmes enceintes pour préparer le corps à l\'accouchement.', category: 'Yoga', difficulty: 'Débutant', weeks: 10, sessionsPerWeek: 2, sessionMinutes: 60, price: 30000, oldPrice: null, coach: 'Lydie Essomba', coachAvatar: null, city: 'Douala', rating: 4.9, reviews: 38, enrolled: 95, type: 'En présentiel', popular: false, recommended: false, image: null, color: '#8B5CF6' },
  { id: 25, title: 'HIIT 21 Jours Challenge', description: 'Transformez votre corps en 21 jours avec des séances HIIT courtes mais intenses, accessibles à tous.', category: 'Cardio', difficulty: 'Intermédiaire', weeks: 3, sessionsPerWeek: 6, sessionMinutes: 30, price: 10000, oldPrice: 15000, coach: 'Sarah Ndjock', coachAvatar: null, city: 'Yaoundé', rating: 4.7, reviews: 92, enrolled: 340, type: 'En ligne', popular: true, recommended: true, image: null, color: '#F97316' },
];

const COACHES = [...new Set(MOCK_PROGRAMS.map((p) => p.coach))];
const CITIES = [...new Set(MOCK_PROGRAMS.map((p) => p.city))];
const CATEGORIES = [...new Set(MOCK_PROGRAMS.map((p) => p.category))];
const DIFFICULTIES = ['Débutant', 'Intermédiaire', 'Avancé'];

export { MOCK_PROGRAMS as programs, COACHES, CITIES, CATEGORIES, DIFFICULTIES };
